easy_admin:
    # site_name: 'Apocalyparc'
    design:
        # form_theme:
        #     - '@EasyAdmin/form/bootstrap_4.html.twig'
        # menu:
        #     - { entity: '', label: '', icon: '' }
        #     - { entity: '', label: '', icon: '' }


    entities:
        # List the entity class name you want to manage
        
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User
