vich_uploader:
    db_driver: orm

    mappings:
        featured_images:
            # variable créée dans service.yaml
            uri_prefix: "/uploads/attraction"
            # namer interne à Vich renomme les fichiers de façon unique
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            upload_destination: '%kernel.project_dir%/public/uploads/attraction'
