<?php

namespace Container2bDLA9x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GS8dD9ZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gS8dD9Z' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gS8dD9Z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'attraction' => ['privates', '.errored..service_locator.gS8dD9Z.App\\Entity\\Attraction', NULL, 'Cannot autowire service ".service_locator.gS8dD9Z": it references class "App\\Entity\\Attraction" but no such service exists.'],
        ], [
            'attraction' => 'App\\Entity\\Attraction',
        ]);
    }
}
