<?php

namespace Container2bDLA9x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAttractionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.gS8dD9Z.App\Entity\Attraction' shared service.
     *
     * @return \App\Entity\Attraction
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.gS8dD9Z": it references class "App\\Entity\\Attraction" but no such service exists.');
    }
}
