<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerO6rx1Hs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerO6rx1Hs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerO6rx1Hs.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerO6rx1Hs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerO6rx1Hs\App_KernelDevDebugContainer([
    'container.build_hash' => 'O6rx1Hs',
    'container.build_id' => 'b702838b',
    'container.build_time' => 1599671173,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerO6rx1Hs');
